apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: deny-public-load-balancers
webhooks:
  - name: deny-public-load-balancers.questionable.services
    sideEffects: None
    # matchPolicy: Equivalent
    rules:
      - apiGroups:
          - "*"
        apiVersions:
          - "v1"
        operations:
          - "CREATE"
          - "UPDATE"
        resources:
          - "services"
    failurePolicy: Fail
    clientConfig:
      url: "https://deny-it-sflxj773na-uc.a.run.app/admission-control/deny-public-services/gcp"

